export type LayoutControl =
  | { key: string; label: string; input: "number"; step?: number; min?: number; max?: number }
  | { key: string; label: string; input: "checkbox" }
  | { key: string; label: string; input: "text" }
  | { key: string; label: string; input: "select"; options: Array<{ value: string; label: string }> };

export type LayoutFamilyMeta = {
  id: string;
  order: number;
  label: string;
  description: string;
  bestFor: string[];
};

export type LayoutAlgorithmMeta = {
  id: string;
  label: string;
  familyId: string;
  subgroupLabel?: string;
  status: "runnable" | "reference";
  kind: "browser_local_layout" | "reference_layout" | "exported_coordinate";
  summary: string;
  usedFor: string;
  bestFor: string[];
  controls?: LayoutControl[];
};

function numberControl(key: string, label: string, step?: number, min?: number, max?: number): LayoutControl {
  return { key, label, input: "number", step, min, max };
}

function checkboxControl(key: string, label: string): LayoutControl {
  return { key, label, input: "checkbox" };
}

function textControl(key: string, label: string): LayoutControl {
  return { key, label, input: "text" };
}

function selectControl(key: string, label: string, options: Array<{ value: string; label: string }>): LayoutControl {
  return { key, label, input: "select", options };
}

function entry(meta: LayoutAlgorithmMeta): LayoutAlgorithmMeta {
  return meta;
}

export const DEFAULT_LAYOUT_FAMILIES: LayoutFamilyMeta[] = [
  {
    id: "force_directed",
    order: 1,
    label: "1. Force-Directed Layout Algorithms",
    description: "Nodes repel while edges pull related nodes together. This is the default exploratory family for network structure.",
    bestFor: ["community detection visuals", "social networks", "exploratory graph interfaces"],
  },
  {
    id: "hierarchical",
    order: 2,
    label: "2. Hierarchical / Layered Layouts",
    description: "Directional structure is arranged into layers so operators can read pipelines, dependencies, or staged flow.",
    bestFor: ["flowcharts", "DAG visualizations", "dependency graphs"],
  },
  {
    id: "tree",
    order: 3,
    label: "3. Tree Layout Algorithms",
    description: "Specialized hierarchical layouts for acyclic structures where ancestry and branching depth matter more than cluster density.",
    bestFor: ["trees", "taxonomies", "branching provenance"],
  },
  {
    id: "circular",
    order: 4,
    label: "4. Circular Layout Algorithms",
    description: "Nodes are placed on one or more circles to expose order, groups, and dense adjacency around a ring.",
    bestFor: ["cluster inspection", "adjacency circles", "connectome-style inspection"],
  },
  {
    id: "spectral",
    order: 5,
    label: "5. Spectral Layout Algorithms",
    description: "Graph matrices are decomposed so global structure emerges from eigenvectors, stress minimization, or embedding distance.",
    bestFor: ["global structure", "dimensionality reduction", "coarse topology reading"],
  },
  {
    id: "multilevel",
    order: 6,
    label: "6. Multilevel / Coarsening Layout Algorithms",
    description: "Large graphs are coarsened, laid out, and expanded again so scale stays tractable without pretending every node can be optimized at once.",
    bestFor: ["very large graphs", "performance scaling", "coarse-to-fine layout"],
  },
  {
    id: "constraint",
    order: 7,
    label: "7. Constraint-Based Layout Algorithms",
    description: "Geometric rules and optimization constraints shape the result, which is useful when readability depends on obeying specific structure.",
    bestFor: ["diagramming", "layout constraints", "overlap control"],
  },
  {
    id: "orthogonal",
    order: 8,
    label: "8. Orthogonal / Grid Layout Algorithms",
    description: "Edges run in horizontal and vertical channels for engineering-style diagrams.",
    bestFor: ["circuit diagrams", "UML", "box-and-arrow schematics"],
  },
  {
    id: "planar",
    order: 9,
    label: "9. Planar Graph Layout Algorithms",
    description: "These specialize in planar graphs where crossings can be avoided or heavily constrained.",
    bestFor: ["planar graphs", "embedding studies", "crossing minimization"],
  },
  {
    id: "geographic",
    order: 10,
    label: "10. Geographic / Coordinate-Anchored Layouts",
    description: "Real coordinates or fixed anchors dominate the placement, so layout respects external geography or measured positions.",
    bestFor: ["transport", "telecom maps", "anchored infrastructure"],
  },
  {
    id: "community",
    order: 11,
    label: "11. Community / Cluster Layout Algorithms",
    description: "Cluster structure guides placement so modularity and neighborhoods remain legible even before detailed inspection.",
    bestFor: ["Louvain / Leiden overlays", "cluster inspection", "group-first reading"],
  },
  {
    id: "edge_bundling",
    order: 12,
    label: "12. Edge Bundling Techniques",
    description: "Not layouts by themselves, but clutter-reduction passes layered on top of an existing layout.",
    bestFor: ["dense edges", "readability cleanup", "flow corridors"],
  },
];

export const DEFAULT_LAYOUT_CATALOG: Record<string, LayoutAlgorithmMeta> = {
  fruchterman_reingold: entry({
    id: "fruchterman_reingold",
    label: "Fruchterman-Reingold",
    familyId: "force_directed",
    subgroupLabel: "Classic algorithms",
    status: "runnable",
    kind: "browser_local_layout",
    summary: "Classic spring-electrical layout that spreads nodes evenly while pulling connected nodes together.",
    usedFor: "Use it when you want a readable, medium-scale exploratory view with simple spring semantics.",
    bestFor: ["community detection visuals", "social networks", "exploratory graph interfaces"],
    controls: [
      numberControl("iterations", "Iterations", 1, 20),
      numberControl("gravity", "Gravity", 0.01, 0),
      numberControl("speed", "Speed", 0.01, 0.01),
      numberControl("cooling", "Cooling", 0.01, 0.5, 0.99),
      checkboxControl("preventOverlap", "Prevent overlap"),
    ],
  }),
  kamada_kawai: entry({
    id: "kamada_kawai",
    label: "Kamada-Kawai",
    familyId: "force_directed",
    subgroupLabel: "Classic algorithms",
    status: "runnable",
    kind: "browser_local_layout",
    summary: "Stress-minimization spring layout that tries to preserve graph-theoretic distances in the drawing.",
    usedFor: "Use it when distance fidelity matters more than raw scale, especially for smaller graphs or path-heavy structure.",
    bestFor: ["distance-preserving views", "path structure", "small-to-medium graphs"],
    controls: [
      numberControl("iterations", "Iterations", 1, 20),
      numberControl("springLength", "Spring length", 0.1, 0.1),
      numberControl("springStrength", "Spring strength", 0.01, 0.01),
      numberControl("cooling", "Cooling", 0.01, 0.01),
    ],
  }),
  eades: entry({
    id: "eades",
    label: "Eades",
    familyId: "force_directed",
    subgroupLabel: "Classic algorithms",
    status: "reference",
    kind: "reference_layout",
    summary: "One of the earliest spring embedders with logarithmic attraction and inverse-square repulsion.",
    usedFor: "Use it as a historical baseline when comparing later force models; not executed in the current worker.",
    bestFor: ["historical baselines", "small graphs"],
  }),
  davidson_harel: entry({
    id: "davidson_harel",
    label: "Davidson-Harel",
    familyId: "force_directed",
    subgroupLabel: "Classic algorithms",
    status: "reference",
    kind: "reference_layout",
    summary: "Simulated-annealing style layout that optimizes multiple aesthetic criteria at once.",
    usedFor: "Use it when you want a reference point for annealing-based aesthetics rather than fast interactive layout.",
    bestFor: ["aesthetic optimization", "small hand-tuned graphs"],
  }),
  forceatlas: entry({
    id: "forceatlas",
    label: "ForceAtlas",
    familyId: "force_directed",
    subgroupLabel: "Modern / scalable variants",
    status: "reference",
    kind: "reference_layout",
    summary: "Gephi's original continuous force model before ForceAtlas2 refined the scale/readability tradeoffs.",
    usedFor: "Use it as a conceptual predecessor to ForceAtlas2 when comparing Gephi-era force models.",
    bestFor: ["Gephi lineage", "exploratory force models"],
  }),
  forceatlas2: entry({
    id: "forceatlas2",
    label: "ForceAtlas2",
    familyId: "force_directed",
    subgroupLabel: "Modern / scalable variants",
    status: "runnable",
    kind: "browser_local_layout",
    summary: "Gephi's best-known force layout, balancing readability, scale, and cluster separation.",
    usedFor: "Use it as the default exploratory layout for medium and large networks where community shape matters.",
    bestFor: ["community detection visuals", "social networks", "exploratory graph interfaces"],
    controls: [
      numberControl("iterations", "Iterations", 1, 20),
      numberControl("scalingRatio", "Scaling ratio", 0.1, 0.1),
      numberControl("gravity", "Gravity", 0.1, 0),
      numberControl("barnesHutTheta", "Barnes-Hut theta", 0.1, 0.1),
      numberControl("edgeWeightInfluence", "Edge weight influence", 0.1, 0),
      checkboxControl("strongGravityMode", "Strong gravity"),
      checkboxControl("barnesHutOptimize", "Barnes-Hut"),
      checkboxControl("linLogMode", "LinLog"),
      checkboxControl("outboundAttractionDistribution", "Outbound attraction distribution"),
      checkboxControl("adjustSizes", "Adjust sizes"),
      checkboxControl("preventOverlap", "Prevent overlap"),
    ],
  }),
  yifan_hu_multilevel: entry({
    id: "yifan_hu_multilevel",
    label: "Yifan Hu Multilevel",
    familyId: "force_directed",
    subgroupLabel: "Modern / scalable variants",
    status: "reference",
    kind: "reference_layout",
    summary: "A multilevel force approach that coarsens large graphs before refinement.",
    usedFor: "Use it when you need a reference for scalable force layouts beyond the current browser worker budget.",
    bestFor: ["large graphs", "multilevel force layout"],
  }),
  openord: entry({
    id: "openord",
    label: "OpenOrd",
    familyId: "force_directed",
    subgroupLabel: "Modern / scalable variants",
    status: "reference",
    kind: "reference_layout",
    summary: "A large-scale layout optimized for exposing cluster structure in sparse massive graphs.",
    usedFor: "Use it as a reference when scale and coarse cluster revelation matter more than local distance fidelity.",
    bestFor: ["massive sparse graphs", "cluster revelation"],
  }),
  linlog: entry({
    id: "linlog",
    label: "LinLog / r-PolyLog",
    familyId: "force_directed",
    subgroupLabel: "Modern / scalable variants",
    status: "runnable",
    kind: "browser_local_layout",
    summary: "A force-energy model that exaggerates separation between communities by favoring cluster structure.",
    usedFor: "Use it when community boundaries are more important than smooth global spacing.",
    bestFor: ["community detection visuals", "cluster-first reading"],
    controls: [
      numberControl("iterations", "Iterations", 1, 20),
      numberControl("scalingRatio", "Scaling ratio", 0.1, 0.1),
      numberControl("gravity", "Gravity", 0.1, 0),
      numberControl("edgeWeightInfluence", "Edge weight influence", 0.1, 0),
      checkboxControl("adjustSizes", "Adjust sizes"),
      checkboxControl("preventOverlap", "Prevent overlap"),
    ],
  }),
  d3_force: entry({
    id: "d3_force",
    label: "D3 Force Layout",
    familyId: "force_directed",
    subgroupLabel: "Modern / scalable variants",
    status: "reference",
    kind: "reference_layout",
    summary: "Interactive force simulation popular in web visualization stacks, usually combining link, charge, and centering forces.",
    usedFor: "Use it as a conceptual web-force reference; the current browser worker does not ship the D3 runtime.",
    bestFor: ["interactive web graph UIs", "custom force tuning"],
  }),
  fm3: entry({
    id: "fm3",
    label: "FM3",
    familyId: "force_directed",
    subgroupLabel: "Modern / scalable variants",
    status: "reference",
    kind: "reference_layout",
    summary: "Fast multipole multilevel method for large force-directed layouts.",
    usedFor: "Use it as a reference when evaluating fast multipole scaling beyond the current browser implementation.",
    bestFor: ["very large graphs", "fast multipole force layout"],
  }),
  gem: entry({
    id: "gem",
    label: "GEM",
    familyId: "force_directed",
    subgroupLabel: "Modern / scalable variants",
    status: "reference",
    kind: "reference_layout",
    summary: "Graph Embedder heuristic combining local and global forces.",
    usedFor: "Use it as a comparative reference for alternative force heuristics.",
    bestFor: ["heuristic force layout", "legacy graph drawing"],
  }),
  sugiyama_layered: entry({
    id: "sugiyama_layered",
    label: "Sugiyama layout",
    familyId: "hierarchical",
    subgroupLabel: "Sugiyama framework family",
    status: "runnable",
    kind: "browser_local_layout",
    summary: "A layered DAG-style view that assigns ranks and spaces nodes so direction reads clearly.",
    usedFor: "Use it for flows, dependencies, or turn-to-turn causality where vertical or horizontal stage order matters.",
    bestFor: ["flowcharts", "DAG visualizations", "dependency graphs"],
    controls: [
      selectControl("orientation", "Orientation", [
        { value: "top_down", label: "Top down" },
        { value: "left_right", label: "Left to right" },
      ]),
      numberControl("layerSpacing", "Layer spacing", 0.1, 0.5),
      numberControl("nodeSpacing", "Node spacing", 0.1, 0.5),
    ],
  }),
  network_simplex: entry({
    id: "network_simplex",
    label: "Network Simplex",
    familyId: "hierarchical",
    subgroupLabel: "Sugiyama framework family",
    status: "reference",
    kind: "reference_layout",
    summary: "Layer assignment optimization commonly used inside Graphviz dot.",
    usedFor: "Use it as the reference ranking stage when you need tighter layered optimization than the current browser heuristic.",
    bestFor: ["layer assignment", "dot-style layout"],
  }),
  brandes_kopf: entry({
    id: "brandes_kopf",
    label: "Brandes-Kopf",
    familyId: "hierarchical",
    subgroupLabel: "Sugiyama framework family",
    status: "reference",
    kind: "reference_layout",
    summary: "Coordinate assignment method for layered graphs after rank calculation.",
    usedFor: "Use it as a reference when comparing layered node ordering and coordinate assignment schemes.",
    bestFor: ["layered coordinate assignment"],
  }),
  coffman_graham: entry({
    id: "coffman_graham",
    label: "Coffman-Graham layering",
    familyId: "hierarchical",
    subgroupLabel: "Sugiyama framework family",
    status: "reference",
    kind: "reference_layout",
    summary: "Width-bounded layering strategy for partially ordered sets.",
    usedFor: "Use it as a reference when width constraints are part of the layered drawing problem.",
    bestFor: ["bounded-width DAGs", "layering heuristics"],
  }),
  reingold_tilford: entry({
    id: "reingold_tilford",
    label: "Reingold-Tilford",
    familyId: "tree",
    subgroupLabel: "Common tree layouts",
    status: "reference",
    kind: "reference_layout",
    summary: "Classic tidy tree algorithm for compact, symmetric rooted trees.",
    usedFor: "Use it as the tidy-tree reference when compact rooted tree presentation matters.",
    bestFor: ["tidy trees", "rooted hierarchies"],
  }),
  walker_tree: entry({
    id: "walker_tree",
    label: "Walker algorithm",
    familyId: "tree",
    subgroupLabel: "Common tree layouts",
    status: "reference",
    kind: "reference_layout",
    summary: "Tree-drawing method that improves subtree spacing over early tidy-tree layouts.",
    usedFor: "Use it as a reference for improved subtree placement in rooted hierarchies.",
    bestFor: ["tidy trees", "subtree spacing"],
  }),
  buchheim_tree: entry({
    id: "buchheim_tree",
    label: "Buchheim tree layout",
    familyId: "tree",
    subgroupLabel: "Common tree layouts",
    status: "reference",
    kind: "reference_layout",
    summary: "Linear-time refinement of tidy tree drawing.",
    usedFor: "Use it as the efficient tidy-tree reference for large rooted trees.",
    bestFor: ["large trees", "linear-time tidy layout"],
  }),
  radial_tree: entry({
    id: "radial_tree",
    label: "Radial tree layout",
    familyId: "tree",
    subgroupLabel: "Common tree layouts",
    status: "runnable",
    kind: "browser_local_layout",
    summary: "Tree-like breadth layers are wrapped around a root so depth expands in rings.",
    usedFor: "Use it when you want rooted hierarchy without consuming the full width of the canvas.",
    bestFor: ["acyclic hierarchies", "rooted neighborhoods", "radial ancestry"],
    controls: [
      selectControl("rootStrategy", "Root strategy", [
        { value: "highest_degree", label: "Highest degree" },
        { value: "selected", label: "Selected node" },
        { value: "explicit", label: "Explicit node id" },
      ]),
      numberControl("ringSpacing", "Ring spacing", 0.1, 0.5),
      numberControl("spread", "Angular spread", 0.1, 0.5, 6.28),
      textControl("rootNodeId", "Root node id"),
    ],
  }),
  balloon_tree: entry({
    id: "balloon_tree",
    label: "Balloon tree",
    familyId: "tree",
    subgroupLabel: "Common tree layouts",
    status: "reference",
    kind: "reference_layout",
    summary: "Children are placed on circles around their parent, producing nested balloons.",
    usedFor: "Use it as a reference for radial subtree packing and hierarchy nesting.",
    bestFor: ["radial subtree packing", "nested hierarchies"],
  }),
  hv_tree: entry({
    id: "hv_tree",
    label: "HV-tree layout",
    familyId: "tree",
    subgroupLabel: "Common tree layouts",
    status: "reference",
    kind: "reference_layout",
    summary: "Alternates horizontal and vertical expansion levels for tree readability.",
    usedFor: "Use it when alternating orientation by depth improves local legibility.",
    bestFor: ["alternating tree layouts", "compact engineering trees"],
  }),
  dendrogram: entry({
    id: "dendrogram",
    label: "Dendrogram layout",
    familyId: "tree",
    subgroupLabel: "Variants",
    status: "reference",
    kind: "reference_layout",
    summary: "Tree drawing optimized for hierarchical clustering output.",
    usedFor: "Use it as the canonical cluster-hierarchy tree reference.",
    bestFor: ["hierarchical clustering", "taxonomy display"],
  }),
  icicle_tree: entry({
    id: "icicle_tree",
    label: "Icicle tree",
    familyId: "tree",
    subgroupLabel: "Variants",
    status: "reference",
    kind: "reference_layout",
    summary: "Space-filling tree layout using layered rectangles.",
    usedFor: "Use it when depth and partition size matter more than edge tracing.",
    bestFor: ["space-filling trees", "hierarchy partitioning"],
  }),
  radial_dendrogram: entry({
    id: "radial_dendrogram",
    label: "Radial dendrogram",
    familyId: "tree",
    subgroupLabel: "Variants",
    status: "reference",
    kind: "reference_layout",
    summary: "Dendrogram wrapped onto a circle for compact cluster hierarchy inspection.",
    usedFor: "Use it when the cluster tree should remain radial rather than linear.",
    bestFor: ["radial clustering trees"],
  }),
  simple_circular: entry({
    id: "simple_circular",
    label: "Simple circular layout",
    familyId: "circular",
    subgroupLabel: "Common versions",
    status: "runnable",
    kind: "browser_local_layout",
    summary: "Places all nodes on a single circle in deterministic order.",
    usedFor: "Use it as the baseline ring view when you want equal spacing and a fast sanity check.",
    bestFor: ["baseline circular views", "adjacency circles"],
    controls: [
      numberControl("radius", "Radius", 0.1, 0.5),
      numberControl("startAngle", "Start angle", 0.1, -6.28, 6.28),
    ],
  }),
  circular_degree: entry({
    id: "circular_degree",
    label: "Circular by degree",
    familyId: "circular",
    subgroupLabel: "Common versions",
    status: "runnable",
    kind: "browser_local_layout",
    summary: "Higher-degree nodes are ordered to stand out earlier around the circle.",
    usedFor: "Use it to inspect hubs, spokes, and role imbalance while keeping a ring-based view.",
    bestFor: ["hub inspection", "degree ordering"],
    controls: [
      numberControl("radius", "Radius", 0.1, 0.5),
      numberControl("startAngle", "Start angle", 0.1, -6.28, 6.28),
    ],
  }),
  circular_community: entry({
    id: "circular_community",
    label: "Circular by community",
    familyId: "circular",
    subgroupLabel: "Common versions",
    status: "runnable",
    kind: "browser_local_layout",
    summary: "Communities occupy ring sectors so clusters remain visually grouped around the circle.",
    usedFor: "Use it when a ring view should still preserve cluster boundaries.",
    bestFor: ["cluster inspection", "adjacency circle diagrams"],
    controls: [
      numberControl("clusterSpacing", "Cluster spacing", 0.1, 1),
      numberControl("intraClusterRadius", "Intra-cluster radius", 0.05, 0.1),
      numberControl("startAngle", "Start angle", 0.1, -6.28, 6.28),
    ],
  }),
  radial: entry({
    id: "radial",
    label: "Radial layout",
    familyId: "circular",
    subgroupLabel: "Common versions",
    status: "runnable",
    kind: "browser_local_layout",
    summary: "A breadth-oriented radial layout centered on a chosen root.",
    usedFor: "Use it for neighborhood inspection when one root should stay central and rings should show distance.",
    bestFor: ["ego networks", "rooted neighborhoods"],
    controls: [
      selectControl("rootStrategy", "Root strategy", [
        { value: "highest_degree", label: "Highest degree" },
        { value: "selected", label: "Selected node" },
        { value: "explicit", label: "Explicit node id" },
      ]),
      textControl("rootNodeId", "Root node id"),
      numberControl("ringSpacing", "Ring spacing", 0.1, 0.5),
    ],
  }),
  chord_layout: entry({
    id: "chord_layout",
    label: "Chord layout",
    familyId: "circular",
    subgroupLabel: "Common versions",
    status: "reference",
    kind: "reference_layout",
    summary: "Circular adjacency summary where ribbons emphasize aggregate connection flow between groups.",
    usedFor: "Use it as a reference for aggregate group-to-group circular diagrams rather than node-level layouts.",
    bestFor: ["aggregate adjacency", "group flow"],
  }),
  laplacian_eigenmap: entry({
    id: "laplacian_eigenmap",
    label: "Laplacian eigenmap layout",
    familyId: "spectral",
    subgroupLabel: "Common methods",
    status: "reference",
    kind: "reference_layout",
    summary: "Spectral placement using Laplacian eigenvectors.",
    usedFor: "Use it as the canonical spectral embedding reference when reading global graph structure.",
    bestFor: ["global structure", "spectral analysis"],
  }),
  spectral_embedding: entry({
    id: "spectral_embedding",
    label: "Spectral embedding",
    familyId: "spectral",
    subgroupLabel: "Common methods",
    status: "reference",
    kind: "reference_layout",
    summary: "Places nodes from low-dimensional eigenvector embeddings.",
    usedFor: "Use it when you want a matrix-derived global view instead of a force simulation.",
    bestFor: ["global structure", "matrix-derived coordinates"],
  }),
  mds: entry({
    id: "mds",
    label: "Multidimensional scaling (MDS)",
    familyId: "spectral",
    subgroupLabel: "Common methods",
    status: "reference",
    kind: "reference_layout",
    summary: "Positions nodes so pairwise distance distortion is minimized.",
    usedFor: "Use it when preserving distance relationships matters more than spring intuition.",
    bestFor: ["distance preservation", "embedding"],
  }),
  pivot_mds: entry({
    id: "pivot_mds",
    label: "Pivot MDS",
    familyId: "spectral",
    subgroupLabel: "Common methods",
    status: "reference",
    kind: "reference_layout",
    summary: "Scalable MDS approximation using pivot points.",
    usedFor: "Use it as the scalable MDS reference for larger graphs.",
    bestFor: ["scalable embedding", "distance approximation"],
  }),
  stress_majorization: entry({
    id: "stress_majorization",
    label: "Stress majorization (SMACOF)",
    familyId: "spectral",
    subgroupLabel: "Common methods",
    status: "reference",
    kind: "reference_layout",
    summary: "Optimization approach that iteratively reduces stress in an embedding.",
    usedFor: "Use it as the reference stress-optimization layout family when comparing distance-preserving methods.",
    bestFor: ["stress minimization", "embedding optimization"],
  }),
  yifan_hu_multilevel_family: entry({
    id: "yifan_hu_multilevel_family",
    label: "Yifan Hu multilevel",
    familyId: "multilevel",
    subgroupLabel: "Important algorithms",
    status: "reference",
    kind: "reference_layout",
    summary: "Coarsen, layout, and refine workflow for large graphs.",
    usedFor: "Use it as a multilevel force reference when scaling beyond the interactive browser worker budget.",
    bestFor: ["large graphs", "multilevel scaling"],
  }),
  fm3_multilevel: entry({
    id: "fm3_multilevel",
    label: "FM3",
    familyId: "multilevel",
    subgroupLabel: "Important algorithms",
    status: "reference",
    kind: "reference_layout",
    summary: "Fast multipole multilevel layout for very large graphs.",
    usedFor: "Use it as the reference when fast multipole scaling becomes necessary.",
    bestFor: ["very large graphs", "fast multipole scaling"],
  }),
  openord_multilevel: entry({
    id: "openord_multilevel",
    label: "OpenOrd",
    familyId: "multilevel",
    subgroupLabel: "Important algorithms",
    status: "reference",
    kind: "reference_layout",
    summary: "Large-scale cluster-oriented layout using multistage optimization.",
    usedFor: "Use it as a reference for cluster-first large-graph placement.",
    bestFor: ["massive sparse graphs", "cluster revelation"],
  }),
  harel_koren: entry({
    id: "harel_koren",
    label: "Harel-Koren multiscale",
    familyId: "multilevel",
    subgroupLabel: "Important algorithms",
    status: "reference",
    kind: "reference_layout",
    summary: "Multiscale force layout emphasizing coarse-to-fine refinement.",
    usedFor: "Use it as a reference for multiscale graph drawing heuristics.",
    bestFor: ["multiscale graph drawing"],
  }),
  grip: entry({
    id: "grip",
    label: "GRIP",
    familyId: "multilevel",
    subgroupLabel: "Important algorithms",
    status: "reference",
    kind: "reference_layout",
    summary: "Graph drawing with intelligent placement and multilevel refinement.",
    usedFor: "Use it as a reference for large-graph coarsening strategies.",
    bestFor: ["large graphs", "multilevel refinement"],
  }),
  constrained_force_directed: entry({
    id: "constrained_force_directed",
    label: "Constrained force-directed",
    familyId: "constraint",
    subgroupLabel: "Examples",
    status: "reference",
    kind: "reference_layout",
    summary: "Force layout with explicit geometric or topological constraints.",
    usedFor: "Use it when force behavior must obey hard diagram rules instead of free exploration.",
    bestFor: ["diagramming constraints", "anchored force layout"],
  }),
  quadratic_programming: entry({
    id: "quadratic_programming",
    label: "Quadratic programming layouts",
    familyId: "constraint",
    subgroupLabel: "Examples",
    status: "reference",
    kind: "reference_layout",
    summary: "Optimization-based layouts solved under explicit quadratic objectives.",
    usedFor: "Use it as the reference for heavily constrained diagram layouts.",
    bestFor: ["constraint optimization", "diagramming"],
  }),
  orthogonal_constraints: entry({
    id: "orthogonal_constraints",
    label: "Orthogonal layouts",
    familyId: "constraint",
    subgroupLabel: "Examples",
    status: "reference",
    kind: "reference_layout",
    summary: "Constraint family where bends and directions obey orthogonal rules.",
    usedFor: "Use it when layout geometry must fit orthogonal engineering conventions.",
    bestFor: ["orthogonal diagrams", "engineering notation"],
  }),
  topology_shape_metrics: entry({
    id: "topology_shape_metrics",
    label: "Topology-shape-metrics",
    familyId: "constraint",
    subgroupLabel: "Examples",
    status: "reference",
    kind: "reference_layout",
    summary: "Optimization family balancing topological correctness, shape, and metric goals.",
    usedFor: "Use it as a reference when diagram quality criteria are multi-objective and explicit.",
    bestFor: ["diagram quality optimization"],
  }),
  noverlap: entry({
    id: "noverlap",
    label: "Noverlap cleanup",
    familyId: "constraint",
    subgroupLabel: "Examples",
    status: "runnable",
    kind: "browser_local_layout",
    summary: "Post-force overlap removal pass that pushes nodes apart while preserving the existing structure as much as possible.",
    usedFor: "Use it after another layout when the main issue is node collision rather than global structure.",
    bestFor: ["overlap control", "post-processing cleanup"],
    controls: [
      numberControl("maxIterations", "Iterations", 1, 20),
      numberControl("margin", "Margin", 1, 0),
      numberControl("ratio", "Ratio", 0.1, 0.1),
      numberControl("speed", "Speed", 0.1, 0.1),
      numberControl("gridSize", "Grid size", 1, 2),
    ],
  }),
  tamassia_orthogonal: entry({
    id: "tamassia_orthogonal",
    label: "Tamassia orthogonal layout",
    familyId: "orthogonal",
    subgroupLabel: "Examples",
    status: "reference",
    kind: "reference_layout",
    summary: "Classic orthogonal graph drawing for planar degree-bounded graphs.",
    usedFor: "Use it as the canonical orthogonal drawing reference for engineering diagrams.",
    bestFor: ["circuit diagrams", "UML"],
  }),
  kandinsky: entry({
    id: "kandinsky",
    label: "Kandinsky model",
    familyId: "orthogonal",
    subgroupLabel: "Examples",
    status: "reference",
    kind: "reference_layout",
    summary: "Orthogonal model allowing multiple edges around higher-degree vertices.",
    usedFor: "Use it as the reference when orthogonal diagrams exceed simple planar degree limits.",
    bestFor: ["complex orthogonal diagrams"],
  }),
  planar_orthogonal: entry({
    id: "planar_orthogonal",
    label: "Planar orthogonal layouts",
    familyId: "orthogonal",
    subgroupLabel: "Examples",
    status: "reference",
    kind: "reference_layout",
    summary: "General family of orthogonal drawings for planar graphs.",
    usedFor: "Use it as the umbrella reference for grid-based planar engineering drawings.",
    bestFor: ["planar engineering diagrams"],
  }),
  tutte_embedding: entry({
    id: "tutte_embedding",
    label: "Tutte embedding",
    familyId: "planar",
    subgroupLabel: "Examples",
    status: "reference",
    kind: "reference_layout",
    summary: "Planar straight-line embedding using a convex boundary.",
    usedFor: "Use it as the classical planar embedding reference when crossings must be avoided analytically.",
    bestFor: ["planar embedding", "crossing-free drawings"],
  }),
  planar_straight_line: entry({
    id: "planar_straight_line",
    label: "Planar straight-line layout",
    familyId: "planar",
    subgroupLabel: "Examples",
    status: "reference",
    kind: "reference_layout",
    summary: "Generic family for drawing planar graphs with straight edges and no crossings.",
    usedFor: "Use it when the graph is known to be planar and a crossing-free straight-line drawing is the goal.",
    bestFor: ["planar graphs"],
  }),
  schnyder_embedding: entry({
    id: "schnyder_embedding",
    label: "Schnyder embedding",
    familyId: "planar",
    subgroupLabel: "Examples",
    status: "reference",
    kind: "reference_layout",
    summary: "Planar embedding based on Schnyder woods and grid coordinates.",
    usedFor: "Use it as a reference for combinatorial planar embedding on grids.",
    bestFor: ["planar combinatorics", "grid embeddings"],
  }),
  geographic_layout: entry({
    id: "geographic_layout",
    label: "Geographic layout",
    familyId: "geographic",
    subgroupLabel: "Examples",
    status: "reference",
    kind: "reference_layout",
    summary: "Uses real-world coordinates as the primary layout signal.",
    usedFor: "Use it when geography is authoritative and the graph should respect physical space first.",
    bestFor: ["transport networks", "telecom infrastructure maps"],
  }),
  map_projection: entry({
    id: "map_projection",
    label: "Map projection layout",
    familyId: "geographic",
    subgroupLabel: "Examples",
    status: "reference",
    kind: "reference_layout",
    summary: "Projects latitude/longitude into a chosen cartographic space.",
    usedFor: "Use it when anchored coordinates need a real map projection rather than raw normalization.",
    bestFor: ["cartographic graph views"],
  }),
  fixed_coordinate: entry({
    id: "fixed_coordinate",
    label: "Fixed coordinate layout",
    familyId: "geographic",
    subgroupLabel: "Examples",
    status: "runnable",
    kind: "browser_local_layout",
    summary: "Keeps provided coordinate anchors and otherwise respects the current positions.",
    usedFor: "Use it when positions come from geography, measurement, or an earlier authoritative export and should not be re-simulated.",
    bestFor: ["anchored coordinates", "fixed maps", "operator-preserved positions"],
    controls: [
      checkboxControl("respectGeoAnchors", "Respect geo anchors"),
      checkboxControl("fallbackToInitial", "Fallback to current coordinates"),
    ],
  }),
  community_clusters: entry({
    id: "community_clusters",
    label: "Cluster-based layout",
    familyId: "community",
    subgroupLabel: "Examples",
    status: "runnable",
    kind: "browser_local_layout",
    summary: "Cluster centroids are spaced apart first, then members are arranged inside each cluster.",
    usedFor: "Use it when group boundaries should dominate the picture before individual edge geometry.",
    bestFor: ["cluster inspection", "community-first reading"],
    controls: [
      numberControl("clusterSpacing", "Cluster spacing", 0.1, 0.5),
      numberControl("intraClusterRadius", "Intra-cluster radius", 0.05, 0.1),
      selectControl("orderBy", "Cluster order", [
        { value: "cluster_size", label: "Cluster size" },
        { value: "label", label: "Label" },
      ]),
    ],
  }),
  linlog_community: entry({
    id: "linlog_community",
    label: "LinLog energy model",
    familyId: "community",
    subgroupLabel: "Examples",
    status: "reference",
    kind: "reference_layout",
    summary: "Community-guided energy model emphasizing modular separation.",
    usedFor: "Use it as the conceptual community-layout reference; the runnable LinLog variant appears in the force-directed family.",
    bestFor: ["cluster separation", "modularity views"],
  }),
  modularity_layout: entry({
    id: "modularity_layout",
    label: "Modularity-based layouts",
    familyId: "community",
    subgroupLabel: "Examples",
    status: "reference",
    kind: "reference_layout",
    summary: "Layout families that explicitly optimize or expose modularity structure.",
    usedFor: "Use it as a reference when clustering directly guides placement.",
    bestFor: ["modularity views", "community-aware placement"],
  }),
  hierarchical_edge_bundling: entry({
    id: "hierarchical_edge_bundling",
    label: "Hierarchical edge bundling",
    familyId: "edge_bundling",
    subgroupLabel: "Common approaches",
    status: "reference",
    kind: "reference_layout",
    summary: "Bundles edges along an existing hierarchy to reduce clutter.",
    usedFor: "Use it after a hierarchy-aware layout when dense cross-links overwhelm the view.",
    bestFor: ["hierarchical clutter reduction"],
  }),
  force_directed_edge_bundling: entry({
    id: "force_directed_edge_bundling",
    label: "Force-directed edge bundling",
    familyId: "edge_bundling",
    subgroupLabel: "Common approaches",
    status: "reference",
    kind: "reference_layout",
    summary: "Curves edges toward shared corridors through force optimization.",
    usedFor: "Use it after layout when dense flows should collapse into readable bundles.",
    bestFor: ["dense edge cleanup", "flow corridors"],
  }),
  geometry_edge_bundling: entry({
    id: "geometry_edge_bundling",
    label: "Geometry-based edge bundling",
    familyId: "edge_bundling",
    subgroupLabel: "Common approaches",
    status: "reference",
    kind: "reference_layout",
    summary: "Uses geometric similarity to group nearby edges into shared bundles.",
    usedFor: "Use it as a post-layout clutter reduction reference when geometry alone should drive bundling.",
    bestFor: ["dense edge cleanup", "geometry-based grouping"],
  }),
};

export const DEFAULT_LAYOUT_DEFAULTS: Record<string, any> = {
  coordinate_mode: "force",
  heavy_graph_node_cap: 320,
  forceatlas2: {
    iterations: 160,
    scalingRatio: 8,
    gravity: 1,
    strongGravityMode: false,
    barnesHutOptimize: true,
    barnesHutTheta: 1.2,
    linLogMode: false,
    outboundAttractionDistribution: false,
    edgeWeightInfluence: 1,
    adjustSizes: false,
    preventOverlap: false,
  },
  fruchterman_reingold: {
    iterations: 120,
    gravity: 0.08,
    speed: 0.18,
    cooling: 0.95,
    preventOverlap: false,
  },
  kamada_kawai: {
    iterations: 80,
    springLength: 1.4,
    springStrength: 0.08,
    cooling: 0.18,
  },
  linlog: {
    iterations: 140,
    scalingRatio: 6,
    gravity: 0.6,
    edgeWeightInfluence: 1,
    adjustSizes: false,
    preventOverlap: false,
  },
  sugiyama_layered: {
    orientation: "top_down",
    layerSpacing: 1.6,
    nodeSpacing: 1.2,
  },
  radial_tree: {
    rootStrategy: "highest_degree",
    ringSpacing: 1.2,
    spread: 6.28,
    rootNodeId: "",
  },
  simple_circular: {
    radius: 1.2,
    startAngle: 0,
  },
  circular_degree: {
    radius: 1.2,
    startAngle: 0,
  },
  circular_community: {
    clusterSpacing: 2.4,
    intraClusterRadius: 0.45,
    startAngle: 0,
  },
  radial: {
    rootStrategy: "highest_degree",
    rootNodeId: "",
    ringSpacing: 1.0,
  },
  noverlap: {
    maxIterations: 160,
    margin: 4,
    ratio: 1.2,
    speed: 3,
    gridSize: 20,
  },
  fixed_coordinate: {
    respectGeoAnchors: true,
    fallbackToInitial: true,
  },
  community_clusters: {
    clusterSpacing: 2.8,
    intraClusterRadius: 0.5,
    orderBy: "cluster_size",
  },
};

export function resolveLayoutFamilies(payloadFamilies?: Array<Partial<LayoutFamilyMeta>> | null): LayoutFamilyMeta[] {
  if (!payloadFamilies?.length) return DEFAULT_LAYOUT_FAMILIES;
  const overrides = new Map(payloadFamilies.map((family) => [String(family.id), family]));
  return DEFAULT_LAYOUT_FAMILIES.map((family) => ({
    ...family,
    ...(overrides.get(family.id) ?? {}),
    bestFor: Array.isArray(overrides.get(family.id)?.bestFor) ? (overrides.get(family.id)?.bestFor as string[]) : family.bestFor,
  }));
}

export function resolveLayoutCatalog(payloadCatalog?: Record<string, any> | null): Record<string, LayoutAlgorithmMeta> {
  const merged: Record<string, LayoutAlgorithmMeta> = {};
  for (const [id, base] of Object.entries(DEFAULT_LAYOUT_CATALOG)) {
    const override = payloadCatalog?.[id] ?? {};
    merged[id] = {
      ...base,
      ...override,
      id,
      bestFor: Array.isArray(override.bestFor) ? override.bestFor : base.bestFor,
      controls: Array.isArray(override.controls) ? override.controls : base.controls,
    };
  }
  for (const [id, value] of Object.entries(payloadCatalog ?? {})) {
    if (merged[id]) continue;
    merged[id] = {
      id,
      label: value?.label ?? id.replaceAll("_", " "),
      familyId: value?.familyId ?? "force_directed",
      subgroupLabel: value?.subgroupLabel,
      status: value?.status ?? (value?.kind === "browser_local_layout" ? "runnable" : "reference"),
      kind: value?.kind ?? "reference_layout",
      summary: value?.summary ?? "Layout terrain item supplied by payload metadata.",
      usedFor: value?.usedFor ?? "Use according to the payload-supplied explanation.",
      bestFor: Array.isArray(value?.bestFor) ? value.bestFor : [],
      controls: Array.isArray(value?.controls) ? value.controls : undefined,
    };
  }
  return merged;
}

export function resolveLayoutDefaults(payloadDefaults?: Record<string, any> | null): Record<string, any> {
  const merged: Record<string, any> = { ...DEFAULT_LAYOUT_DEFAULTS };
  for (const [key, value] of Object.entries(payloadDefaults ?? {})) {
    if (value && typeof value === "object" && !Array.isArray(value)) {
      merged[key] = { ...(DEFAULT_LAYOUT_DEFAULTS[key] ?? {}), ...value };
    } else {
      merged[key] = value;
    }
  }
  return merged;
}

export function humanLayoutLabel(layoutId: string, catalog?: Record<string, LayoutAlgorithmMeta> | null): string {
  if (layoutId.startsWith("layout-run::")) return "Saved layout";
  return catalog?.[layoutId]?.label ?? layoutId.replaceAll("_", " ");
}

export function isRunnableLayout(layoutId: string, catalog?: Record<string, LayoutAlgorithmMeta> | null): boolean {
  return Boolean(catalog?.[layoutId]?.status === "runnable");
}
